## This Dockerfile is auto-generated by scripts/buildDockerfile.ts

FROM node:22-alpine as builder

RUN apk update && apk upgrade

WORKDIR /app-build
COPY .dev.mk .
COPY bin ./bin
COPY package.json .
COPY package-lock.json .
COPY rollup.config.mjs .
COPY tsconfig.json .
COPY scripts ./scripts
COPY src ./src
COPY static ./static
RUN npm ci && NODE_ENV=production node_modules/.bin/rollup -c && npm pack && mv *.tgz /tmp/app.tgz

WORKDIR /app
RUN npm install --no-optional --no-package-lock /tmp/app.tgz && rm -f /tmp/app.tgz && rm -rf /app-build && npm cache clean --force

ENV NODE_ENV=production \
 DM_PORT="8081" \
 DM_PLUGINS=core/static,core/helloworld \
 DM_LDAP_BASE= \
 DM_LDAP_DN="cn=admin,dc=example,dc=org" \
 DM_LDAP_PWD="admin" \
 DM_LDAP_URL="ldap://localhost" \
 DM_TOP_DN="dc=example,dc=com" \
 DM_SCHEMAS_PATH="/app/node_modules/mini-dm/static/schemas" \
 DM_MAIL_ATTRIBUTE="mail" \
 DM_USER_CLASSES=top,inetOrgPerson \
 DM_LDAP_GROUP_BASE= \
 DM_LDAP_GROUPS_MAIN_ATTRIBUTE="cn" \
 DM_GROUP_CLASSES=top,groupOfNames \
 DM_ALLOW_UNEXISTENT_MEMBERS=false \
 DM_GROUP_DEFAULT_ATTRIBUTES="{}" \
 DM_GROUP_DUMMY_USER="cn=fakeuser" \
 DM_EXTERNAL_MEMBERS_BRANCH="ou=contacts,dc=example,dc=com" \
 DM_STATIC_PATH="/app/node_modules/mini-dm/static" \
 DM_STATIC_NAME="static" \
 DM_LLNG_INI="/etc/lemonldap-ng/lemonldap-ng.ini"

EXPOSE 8081
CMD ["npx", "mini-dm"]
